#!/bin/sh
sbatch --export=ALL,shID=1 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=2 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=3 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=4 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=5 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=6 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=7 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=8 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=9 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=10 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=11 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=12 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=13 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=14 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=15 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=16 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=17 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=18 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=19 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=20 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=21 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=22 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=23 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=24 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=25 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=26 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=27 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=28 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=29 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=30 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=31 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=32 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=33 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=34 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=35 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=36 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=37 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=38 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=39 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=40 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=41 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=42 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=43 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=44 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=45 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=46 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=47 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=48 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=49 RunXGBoostWithCovs.sh
sbatch --export=ALL,shID=50 RunXGBoostWithCovs.sh
