#!/bin/sh
sbatch --export=ALL,shID=1,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=2,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=3,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=4,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=5,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=6,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=7,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=8,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=9,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=10,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=11,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=12,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=13,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=14,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=15,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=16,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=17,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=18,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=19,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=20,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=21,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=22,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=23,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=24,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=25,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=26,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=27,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=28,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=29,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=30,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=31,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=32,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=33,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=34,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=35,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=36,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=37,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=38,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=39,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=40,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=41,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=42,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=43,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=44,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=45,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=46,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=47,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=48,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=49,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh
sbatch --export=ALL,shID=50,eta=0.05,colsample_bylevel=0.8,subsample=0.8,colsample_bytree=0.8,max_depth=2,nthreads=20 RunXGBoostAllFoldsInCV.sh

