#!/bin/sh
sbatch --export=ALL,shID=1 PrepareGWASdata.sh
sbatch --export=ALL,shID=2 PrepareGWASdata.sh
sbatch --export=ALL,shID=3 PrepareGWASdata.sh
sbatch --export=ALL,shID=4 PrepareGWASdata.sh
sbatch --export=ALL,shID=5 PrepareGWASdata.sh
sbatch --export=ALL,shID=6 PrepareGWASdata.sh
sbatch --export=ALL,shID=7 PrepareGWASdata.sh
sbatch --export=ALL,shID=8 PrepareGWASdata.sh
sbatch --export=ALL,shID=9 PrepareGWASdata.sh
sbatch --export=ALL,shID=10 PrepareGWASdata.sh
sbatch --export=ALL,shID=11 PrepareGWASdata.sh
sbatch --export=ALL,shID=12 PrepareGWASdata.sh
sbatch --export=ALL,shID=13 PrepareGWASdata.sh
sbatch --export=ALL,shID=14 PrepareGWASdata.sh
sbatch --export=ALL,shID=15 PrepareGWASdata.sh
sbatch --export=ALL,shID=16 PrepareGWASdata.sh
sbatch --export=ALL,shID=17 PrepareGWASdata.sh
sbatch --export=ALL,shID=18 PrepareGWASdata.sh
sbatch --export=ALL,shID=19 PrepareGWASdata.sh
sbatch --export=ALL,shID=20 PrepareGWASdata.sh
sbatch --export=ALL,shID=21 PrepareGWASdata.sh
sbatch --export=ALL,shID=22 PrepareGWASdata.sh
sbatch --export=ALL,shID=23 PrepareGWASdata.sh
sbatch --export=ALL,shID=24 PrepareGWASdata.sh
sbatch --export=ALL,shID=25 PrepareGWASdata.sh
sbatch --export=ALL,shID=26 PrepareGWASdata.sh
sbatch --export=ALL,shID=27 PrepareGWASdata.sh
sbatch --export=ALL,shID=28 PrepareGWASdata.sh
sbatch --export=ALL,shID=29 PrepareGWASdata.sh
sbatch --export=ALL,shID=30 PrepareGWASdata.sh
sbatch --export=ALL,shID=31 PrepareGWASdata.sh
sbatch --export=ALL,shID=32 PrepareGWASdata.sh
sbatch --export=ALL,shID=33 PrepareGWASdata.sh
sbatch --export=ALL,shID=34 PrepareGWASdata.sh
sbatch --export=ALL,shID=35 PrepareGWASdata.sh
sbatch --export=ALL,shID=36 PrepareGWASdata.sh
sbatch --export=ALL,shID=37 PrepareGWASdata.sh
sbatch --export=ALL,shID=38 PrepareGWASdata.sh
sbatch --export=ALL,shID=39 PrepareGWASdata.sh
sbatch --export=ALL,shID=40 PrepareGWASdata.sh
sbatch --export=ALL,shID=41 PrepareGWASdata.sh
sbatch --export=ALL,shID=42 PrepareGWASdata.sh
sbatch --export=ALL,shID=43 PrepareGWASdata.sh
sbatch --export=ALL,shID=44 PrepareGWASdata.sh
sbatch --export=ALL,shID=45 PrepareGWASdata.sh
sbatch --export=ALL,shID=46 PrepareGWASdata.sh
sbatch --export=ALL,shID=47 PrepareGWASdata.sh
sbatch --export=ALL,shID=48 PrepareGWASdata.sh
sbatch --export=ALL,shID=49 PrepareGWASdata.sh
sbatch --export=ALL,shID=50 PrepareGWASdata.sh
