#!/bin/sh
sbatch --export=ALL,shID=1 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=2 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=3 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=4 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=5 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=6 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=7 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=8 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=9 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=10 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=11 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=12 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=13 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=14 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=15 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=16 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=17 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=18 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=19 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=20 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=21 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=22 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=23 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=24 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=25 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=26 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=27 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=28 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=29 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=30 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=31 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=32 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=33 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=34 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=35 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=36 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=37 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=38 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=39 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=40 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=41 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=42 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=43 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=44 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=45 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=46 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=47 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=48 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=49 PrepareGWASdataIndepSNPs.sh
sbatch --export=ALL,shID=50 PrepareGWASdataIndepSNPs.sh
